// Generated by dia2code
#ifndef STATE__BATIMENT__H
#define STATE__BATIMENT__H


namespace state {
  class Position;
  class Unite;
}

#include "Position.h"
#include "Unite.h"

namespace state {

  /// class Batiment - 
  class Batiment {
    // Associations
    // Attributes
  public:
    Position position;
    int color;
    int id_b;
    // Operations
  public:
    Batiment ();
    Batiment (Position position, int color);
    virtual int getId_b ();
    virtual int getColor ();
    virtual int getTileId ();
    virtual ~Batiment ();
    virtual Unite* creerU (int id);
    // Setters and Getters
  };

};

#endif
