// Generated by dia2code
#ifndef STATE__BATIMENT__H
#define STATE__BATIMENT__H


namespace state {
  class Position;
}

#include "Position.h"

namespace state {

  /// class Batiment - 
  class Batiment {
    // Associations
    // Attributes
  public:
    Position position;
    int color;
    int id_b;
    // Operations
  public:
    Batiment ();
    Batiment (Position position, int color);
    virtual int getId_b ();
    virtual int getColor ();
    virtual ~Batiment ();
    // Setters and Getters
  };

};

#endif
