#include <vector>
#include "carte.h"

std::vector<std::vector<state::TerrainTypeId>> map1() {
	std::vector<std::vector<state::TerrainTypeId>> carte1;
	carte1 = {{state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::foret,state::foret,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::foret,state::foret,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine},
	{state::route,state::route,state::route,state::route,state::plaine,state::foret,state::foret,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::foret,state::foret,state::plaine,state::route,state::route,state::route,state::route},
	{state::montagne,state::plaine,state::plaine,state::route,state::plaine,state::foret,state::foret,state::foret,state::foret,state::plaine,state::plaine,state::foret,state::foret,state::foret,state::foret,state::plaine,state::route,state::plaine,state::plaine,state::montagne},
	{state::montagne,state::montagne,state::plaine,state::route,state::plaine,state::plaine,state::plaine,state::plaine,state::foret,state::foret,state::foret,state::foret,state::plaine,state::plaine,state::plaine,state::plaine,state::route,state::plaine,state::montagne,state::montagne},
	{state::plaine,state::foret,state::plaine,state::route,state::route,state::route,state::plaine,state::plaine,state::montagne,state::foret,state::foret,state::montagne,state::plaine,state::plaine,state::route,state::route,state::route,state::plaine,state::foret,state::plaine},
	{state::plaine,state::foret,state::foret,state::route,state::plaine,state::route,state::route,state::route,state::route,state::route,state::route,state::route,state::route,state::route,state::route,state::plaine,state::route,state::foret,state::foret,state::plaine},
	{state::plaine,state::plaine,state::route,state::route,state::montagne,state::montagne,state::plaine,state::plaine,state::foret,state::foret,state::foret,state::foret,state::plaine,state::montagne,state::montagne,state::plaine,state::route,state::route,state::plaine,state::plaine},
	{state::plaine,state::plaine,state::route,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::foret,state::montagne,state::montagne,state::foret,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::route,state::plaine,state::plaine},
	{state::plaine,state::plaine,state::route,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::foret,state::montagne,state::montagne,state::foret,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::route,state::plaine,state::plaine},
	{state::plaine,state::plaine,state::route,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::montagne,state::montagne,state::montagne,state::montagne,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::route,state::plaine,state::plaine},
	{state::plaine,state::plaine,state::route,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::montagne,state::montagne,state::montagne,state::montagne,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::route,state::plaine,state::plaine},
	{state::plaine,state::plaine,state::route,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::foret,state::montagne,state::montagne,state::foret,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::route,state::plaine,state::plaine},
	{state::plaine,state::plaine,state::route,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::foret,state::montagne,state::montagne,state::foret,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::route,state::plaine,state::plaine},
	{state::plaine,state::plaine,state::route,state::route,state::montagne,state::montagne,state::plaine,state::plaine,state::foret,state::foret,state::foret,state::foret,state::plaine,state::montagne,state::montagne,state::plaine,state::route,state::route,state::plaine,state::plaine},
	{state::plaine,state::foret,state::foret,state::route,state::plaine,state::route,state::route,state::route,state::route,state::route,state::route,state::route,state::route,state::route,state::route,state::plaine,state::route,state::foret,state::foret,state::plaine},
	{state::plaine,state::foret,state::plaine,state::route,state::route,state::route,state::plaine,state::plaine,state::montagne,state::foret,state::foret,state::montagne,state::plaine,state::plaine,state::route,state::route,state::route,state::plaine,state::foret,state::plaine},
	{state::montagne,state::montagne,state::plaine,state::route,state::plaine,state::plaine,state::plaine,state::plaine,state::foret,state::foret,state::foret,state::foret,state::plaine,state::plaine,state::plaine,state::plaine,state::route,state::plaine,state::montagne,state::montagne},
	{state::montagne,state::plaine,state::plaine,state::route,state::plaine,state::foret,state::foret,state::foret,state::foret,state::plaine,state::plaine,state::foret,state::foret,state::foret,state::foret,state::plaine,state::route,state::plaine,state::plaine,state::montagne},
	{state::route,state::route,state::route,state::route,state::plaine,state::foret,state::foret,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::foret,state::foret,state::plaine,state::route,state::route,state::route,state::route},
	{state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::foret,state::foret,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine,state::foret,state::foret,state::plaine,state::plaine,state::plaine,state::plaine,state::plaine}};
	return(carte1);
};

