// Generated by dia2code
#ifndef STATE__FABRICANT__H
#define STATE__FABRICANT__H


namespace state {
  class Unite;
  class Position;
  class Batiment;
}

#include "Unite.h"
#include "Batiment.h"

namespace state {

  /// class Fabricant - 
  template <  class T>
  class Fabricant : public state::Batiment {
    // Operations
  public:
    Unite creerU (int argent, Position& position);
    // Setters and Getters
  };

};

#endif
