// Generated by dia2code
#ifndef STATE__FLAG__H
#define STATE__FLAG__H


namespace state {
  class Position;
}

#include "Position.h"

namespace state {

  /// class Flag - 
  class Flag {
    // Associations
    // Attributes
  public:
    Position position;
    int color;
    bool is_owned     = false;
    // Operations
  public:
    Flag ();
    Flag (Position position, int color);
    int getTileId ();
    ~Flag ();
    // Setters and Getters
  };

};

#endif
