// Generated by dia2code
#ifndef STATE__HTANK__H
#define STATE__HTANK__H

#include <vector>

namespace state {
  class Position;
  class Unite;
}

#include "Position.h"
#include "Unite.h"

namespace state {

  /// class HTank - 
  class HTank : public state::Unite {
    // Attributes
  public:
    int vie     = 250;
    int prix     = 10000;
    int mvt     = 3;
    int puissance     = 200;
    int id     = 4;
    // Operations
  public:
    HTank ();
    HTank (Position position, int color);
    std::vector<Position> getLegalMove ();
    int getvie ();
    int getprix ();
    int getmvt ();
    int getpuissance ();
    int getId ();
    int getColor ();
    int getTileId ();
    void attacker (Unite* unite);
    void setvie (int v);
    void setpuissance (int p);
    ~HTank ();
    void move (Position position);
    // Setters and Getters
  };

};

#endif
