// Generated by dia2code
#ifndef STATE__INFANTRY__H
#define STATE__INFANTRY__H

#include <vector>

namespace state {
  class Position;
  class Unite;
}

#include "Position.h"
#include "Unite.h"

namespace state {

  /// class Infantry - 
  class Infantry : public state::Unite {
    // Attributes
  public:
    int vie     = 100;
    int prix     = 1000;
    int mvt     = 3;
    int puissance     = 60;
    // Operations
  public:
    Infantry (Position position, int color);
    std::vector<Position> getLegalMove ();
    ~Infantry ();
    // Setters and Getters
  };

};

#endif
