// Generated by dia2code
#ifndef STATE__INFANTRY__H
#define STATE__INFANTRY__H

#include <vector>

namespace state {
  class Position;
  class Unite;
}

#include "Position.h"
#include "Unite.h"

namespace state {

  /// class Infantry - 
  class Infantry : public state::Unite {
    // Attributes
  public:
    int vie     = 100;
    int prix     = 1000;
    int mvt     = 3;
    int puissance     = 60;
    int id     = 0;
    int portee     = 1;
    // Operations
  public:
    Infantry ();
    Infantry (Position position, int color);
    std::vector<Position> getLegalMove ();
    int getvie ();
    int getprix ();
    int getmvt ();
    int getpuissance ();
    int getId ();
    int getColor ();
    int getTileId ();
    void attacker (Unite* unite);
    void setvie (int v);
    void setpuissance (int p);
    ~Infantry ();
    void move (Position position);
    // Setters and Getters
  };

};

#endif
