// Generated by dia2code
#ifndef STATE__JEU__H
#define STATE__JEU__H


namespace state {
  class Terrain;
  class Usine;
}

#include "Usine.h"
#include "Terrain.h"

namespace state {

  /// class Jeu - 
  class Jeu {
    // Associations
    // Attributes
  public:
    Terrain* etatJeu;
    int tour;
    bool fin;
    // Operations
  public:
    Jeu (Terrain* etatJeu);
    ~Jeu ();
    // Setters and Getters
  };

};

#endif
