// Generated by dia2code
#ifndef STATE__JEU__H
#define STATE__JEU__H

#include <vector>

namespace state {
  class Terrain;
  class Joueur;
  class Unite;
}

#include "Joueur.h"
#include "Terrain.h"

namespace state {

  /// class Jeu - 
  class Jeu {
    // Associations
    // Attributes
  public:
    Terrain* etatJeu;
    int tour     = 0;
    bool fin     = false;
    std::vector<Joueur*> joueurs;
    Unite* selectedUnit     = nullptr;
    // Operations
  public:
    Jeu (Terrain* etatJeu, std::vector<Joueur*> joueurs);
    ~Jeu ();
    // Setters and Getters
  };

};

#endif
