// Generated by dia2code
#ifndef STATE__MISCTILE__H
#define STATE__MISCTILE__H


namespace state {
  class Position;
}

#include "Position.h"

namespace state {

  /// class MiscTile - 
  class MiscTile {
    // Associations
    // Attributes
  public:
    int tile_id;
    Position position;
    // Operations
  public:
    MiscTile ();
    MiscTile (int tile_id, Position position);
    int getTileId ();
    ~MiscTile ();
    // Setters and Getters
  };

};

#endif
