// Generated by dia2code
#ifndef STATE__PORTEMONNAIE__H
#define STATE__PORTEMONNAIE__H


namespace state {

  /// class PorteMonnaie - 
  class PorteMonnaie {
    // Attributes
  public:
    int argent;
    // Operations
  public:
    PorteMonnaie ();
    int getargent ();
    int achat (int argent);
    int gaintour (int argent);
    ~PorteMonnaie ();
    // Setters and Getters
  };

};

#endif
