// Generated by dia2code
#ifndef STATE__QG__H
#define STATE__QG__H


namespace state {
  class Position;
  class Batiment;
}

#include "Position.h"
#include "Batiment.h"

namespace state {

  /// class QG - 
  class QG : public state::Batiment {
    // Attributes
  public:
    int id_b     = 0;
    // Operations
  public:
    QG ();
    QG (Position position, int color);
    bool Drapeau_E ();
    bool Drapeau ();
    int getId_b ();
    int getColor ();
    int getTileId ();
    ~QG ();
    // Setters and Getters
  };

};

#endif
