// Generated by dia2code
#ifndef STATE__TANK__H
#define STATE__TANK__H

#include <vector>

namespace state {
  class Position;
  class Unite;
}

#include "Position.h"
#include "Unite.h"

namespace state {

  /// class Tank - 
  class Tank : public state::Unite {
    // Attributes
  public:
    int vie     = 200;
    int prix     = 7000;
    int mvt     = 3;
    int puissance;
    // Operations
  public:
    Tank (Position position, int color);
    std::vector<Position> getLegalMove ();
    // Setters and Getters
  };

};

#endif
