// Generated by dia2code
#ifndef STATE__TANK__H
#define STATE__TANK__H

#include <vector>

namespace state {
  class Position;
  class Terrain;
  class Unite;
}

#include "Position.h"
#include "Unite.h"

namespace state {

  /// class Tank - 
  class Tank : public state::Unite {
    // Attributes
  public:
    int vie     = 200;
    int prix     = 7000;
    int mvt     = 3;
    int puissance     = 180;
    int id     = 3;
    // Operations
  public:
    Tank ();
    Tank (Position position, int color);
    std::vector<Position> getLegalMove (Terrain* terrain);
    int getvie ();
    int getprix ();
    int getmvt ();
    int getpuissance ();
    int getId ();
    int getColor ();
    int getTileId ();
    void setvie (int v);
    void attacker (Unite* unite);
    void setpuissance (int p);
    ~Tank ();
    void move (Position position);
    bool isLegalMove (Position pos, Terrain* terrain);
    // Setters and Getters
  };

};

#endif
