// Generated by dia2code
#ifndef STATE__TERRAINTYPEID__H
#define STATE__TERRAINTYPEID__H


namespace state {

  enum TerrainTypeId {
    plaine     = 0,
    foret     = 1,
    montagne     = 2,
    routeh     = 3,
    routev     = 4,
    routedu     = 5,
    routegu     = 6,
    routedd     = 7,
    routegd     = 8
  };

};

#endif
