// Generated by dia2code
#ifndef STATE__TERRAINTYPEID__H
#define STATE__TERRAINTYPEID__H


namespace state {

  enum TerrainTypeId {
    route     = 0,
    plaine     = 1,
    foret     = 2,
    montagne     = 3,
    ville     = 4
  };

};

#endif
