// Generated by dia2code
#ifndef STATE__TERRAINTAB__H
#define STATE__TERRAINTAB__H

#include <vector>

namespace state {
  class Position;
}

#include "TerrainTypeId.h"
#include "Position.h"

namespace state {

  /// class TerrainTab - 
  class TerrainTab {
    // Attributes
  private:
    std::vector<std::vector<TerrainTypeId>> grid;
    // Operations
  public:
    TerrainTab (std::vector<std::vector<TerrainTypeId>> grid);
    TerrainTab ();
    TerrainTypeId get (Position position);
    ~TerrainTab ();
    // Setters and Getters
  };

};

#endif
