// Generated by dia2code
#ifndef STATE__TERRAIN__H
#define STATE__TERRAIN__H

#include <vector>

namespace state {
  class TerrainTab;
  class Unite;
  class Batiment;
  class Position;
  class TerrainTile;
}

#include "TerrainTab.h"
#include "Position.h"
#include "TerrainTypeId.h"
#include "TerrainTile.h"
#include "Unite.h"
#include "Batiment.h"

namespace state {

  /// class Terrain - 
  class Terrain {
    // Associations
    // Attributes
  private:
    std::vector<std::vector<Unite*>> unites;
    std::vector<std::vector<Batiment*>> batiments;
    TerrainTab sol;
    // Operations
  public:
    Terrain (std::vector<std::vector<Unite*>> unites, std::vector<std::vector<Batiment*>> batiments, TerrainTab sol);
    Terrain ();
    Unite* getUnite (Position position);
    Batiment* getBatiment (Position position);
    TerrainTypeId getGround (Position position);
    void moveUnite (Position pos_init, Position pos_final);
    ~Terrain ();
    // Setters and Getters
  };

};

#endif
