// Generated by dia2code
#ifndef STATE__TERRAINTAB__H
#define STATE__TERRAINTAB__H

#include <vector>

namespace state {
  class Position;
}

#include "TerrainTypeId.h"
#include "Position.h"

namespace state {

  /// class TerrainTab - 
  class TerrainTab {
    // Attributes
  public:
    int width;
    int height;
  private:
    std::vector<std::vector<TerrainTypeId>> list;
    // Operations
  public:
    TerrainTab (int width, int height);
    TerrainTypeId get (Position position);
  private:
    /// 	
    /// @param list		(???) 
    void fill (std::vector<std::vector<TerrainTypeId>> list);
    // Setters and Getters
  };

};

#endif
