// Generated by dia2code
#ifndef STATE__TERRAIN__H
#define STATE__TERRAIN__H

#include <map>

namespace state {
  class TerrainTab;
  class Unite;
  class Position;
  class Batiment;
}

#include "TerrainTab.h"
#include "Unite.h"
#include "Position.h"
#include "Batiment.h"

namespace state {

  /// class Terrain - 
  class Terrain {
    // Associations
    // Attributes
  public:
    std::map<Position, Unite> unites;
    std::map<Position, Batiment> batiments;
    TerrainTab sol;
    // Operations
  public:
    Terrain (std::map<Position, Unite> unites, std::map<Position, Batiment> batiments, TerrainTab sol);
    // Setters and Getters
  };

};

#endif
