// Generated by dia2code
#ifndef STATE__TERRAIN__H
#define STATE__TERRAIN__H

#include <vector>

namespace state {
  class Unite;
  class Batiment;
  class TerrainTab;
  class Position;
  class TerrainTile;
}

#include "TerrainTab.h"
#include "Position.h"
#include "TerrainTypeId.h"
#include "TerrainTile.h"
#include "Unite.h"
#include "Batiment.h"

namespace state {

  /// class Terrain - 
  class Terrain {
    // Associations
    // Attributes
  private:
    std::vector<Unite*> unites;
    std::vector<Batiment*> batiments;
    TerrainTab sol;
    // Operations
  public:
    Terrain (std::vector<Unite*> unites, std::vector<Batiment*> batiments, TerrainTab sol);
    Terrain ();
    Unite* getUnite (Position position);
    Batiment* getBatiment (Position position);
    TerrainTypeId getGround (Position position);
    void addUnite (Unite* unite);
    void deleteUnite (Position position);
    ~Terrain ();
    std::vector<Unite*>& getUniteList ();
    std::vector<Batiment*>& getBatimentList ();
    // Setters and Getters
  };

};

#endif
