// Generated by dia2code
#ifndef STATE__UNITE__H
#define STATE__UNITE__H

#include <vector>

namespace state {
  class Position;
}

#include "Position.h"

namespace state {

  /// class Unite - 
  class Unite {
    // Associations
    // Attributes
  public:
    Position position;
    int color;
    int vie;
    int prix;
    int mvt;
    int puissance;
    int id;
    // Operations
  public:
    Unite ();
    Unite (Position position, int color);
    virtual std::vector<Position> getLegalMove ();
    virtual int getvie ();
    virtual int getprix ();
    virtual int getmvt ();
    virtual int getpuissance ();
    virtual int getId ();
    virtual ~Unite ();
    virtual int getColor ();
    int operator= ();
    // Setters and Getters
  };

};

#endif
