// Generated by dia2code
#ifndef STATE__USINE__H
#define STATE__USINE__H


namespace state {
  class Position;
  class Unite;
  class Batiment;
}

#include "Position.h"
#include "Unite.h"
#include "Batiment.h"

namespace state {

  /// class Usine - 
  template <  typename T>
  class Usine : public state::Batiment {
    // Attributes
  public:
    Position position;
    int color;
    int id_b     = 1;
    // Operations
  public:
    Unite creerU (int argent, Position& position);
    int getId_b ();
    int getColor ();
    // Setters and Getters
  };

};

#endif
