// Generated by dia2code
#ifndef RENDER__LAYERS__H
#define RENDER__LAYERS__H


namespace state {
  class Jeu;
};
class Tileset;
class Surface;
#include "state/Jeu.h"
#include "Tileset.h"
#include "Surface.h"

namespace render {

  /// class Layers - 
  class Layers {
    // Associations
    // Attributes
  public:
    render::Surface uniteSurface;
    render::Surface batimentSurface;
    render::Surface terrainSurface;
    // Operations
  public:
    Layers ();
    ~Layers ();
    void setUniteSurface (state::Terrain* terrain);
    void setBatimentSurface (state::Terrain* terrain);
    void setTerrainSurface (state::Terrain* terrain);
    void displayLayers ();
    // Setters and Getters
  };

};

#endif
