// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H


namespace render {
  class TileSet;
}

#include "TileSet.h"

namespace render {

  /// class Layer - 
  class Layer {
    // Associations
    // Setters and Getters
  };

};

#endif
