// Generated by dia2code
#ifndef RENDER__TERRAINTILESET__H
#define RENDER__TERRAINTILESET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
  class TileSet;
}

#include "Tile.h"
#include "TileSet.h"

namespace render {

  /// class TerrainTileSet - 
  class TerrainTileSet : public render::TileSet {
    // Attributes
  private:
    std::vector<Tile> terrains;
    // Operations
  public:
    TerrainTileSet ();
    ~TerrainTileSet ();
    int const getCellWidth ();
    int const getCellHeight ();
    std::string const getImageFile ();
    Tile&  getTile (std::string c);
    // Setters and Getters
  };

};

#endif
