// Generated by dia2code
#ifndef RENDER__TILEMAP__H
#define RENDER__TILEMAP__H


namespace state {
  class Jeu;
}

#include "state/Jeu.h"

namespace render {

  /// class Tilemap - 
  class Tilemap {
    // Associations
    // Attributes
  public:
    state::Jeu jeu;
    // Setters and Getters
  };

};

#endif
