// Generated by dia2code
#ifndef RENDER__TILEMAP__H
#define RENDER__TILEMAP__H


namespace state {
  class Jeu;
};
namespace render {
  class Layer;
}

#include "state/Jeu.h"
#include "Layer.h"

namespace render {

  /// class Tilemap - 
  class Tilemap : public render::Layer {
    // Associations
    // Attributes
  public:
    state::Jeu jeu;
    // Setters and Getters
  };

};

#endif
