// Generated by dia2code
#ifndef RENDER__TILE__H
#define RENDER__TILE__H


namespace render {

  /// class Tile - 
  class Tile {
    // Operations
  public:
    Tile ();
    ~Tile ();
    // Setters and Getters
  };

};

#endif
