// Generated by dia2code
#ifndef RENDER__TILESET__H
#define RENDER__TILESET__H

#include <string>

namespace render {
  class Tile;
}

#include "Tile.h"

namespace render {

  /// class TileSet - 
  class TileSet {
    // Associations
    // Operations
  public:
    TileSet ();
    ~TileSet ();
    int const getCellWidth ();
    int const getCellHeight ();
    std::string const getImageFile ();
    Tile&  getTile (std::string c);
    // Setters and Getters
  };

};

#endif
