// Generated by dia2code
#ifndef RENDER__UI__H
#define RENDER__UI__H

#include <vector>
#include <SFML/Graphics.hpp>

namespace sf {
  class Font;
  class Text;
  class Sprite;
};
namespace state {
  class Jeu;
};
namespace sf {
  class Texture;
}

#include "state/Jeu.h"

namespace render {

  /// class UI - 
  class UI {
    // Associations
    // Attributes
  public:
    sf::Font font;
    std::vector<sf::Text> generalText;
    std::vector<sf::Text> uniteText;
    std::vector<sf::Sprite> batimentSprites;
    state::Jeu* jeu;
    sf::Texture selBatTexture;
    sf::Texture unitCursorTexture;
    sf::Texture buttonsTexture;
    // Operations
  public:
    UI ();
    UI (state::Jeu* jeu);
    void setGeneralData ();
    void setUnitData ();
    void setBatimentData ();
    void displayUI (sf::RenderWindow* window);
    ~UI ();
    // Setters and Getters
  };

};

#endif
