// Generated by dia2code
#ifndef RENDER__UI__H
#define RENDER__UI__H

#include <vector>
#include <SFML/Graphics.hpp>

namespace sf {
  class Font;
  class Text;
};
namespace state {
  class Jeu;
}

#include "state/Jeu.h"

namespace render {

  /// class UI - 
  class UI {
    // Associations
    // Attributes
  public:
    sf::Font font;
    std::vector<sf::Text> generalText;
    std::vector<sf::Text> uniteText;
    std::vector<sf::Text> batimentText;
    state::Jeu* jeu;
    // Operations
  public:
    UI ();
    UI (state::Jeu* jeu);
    void setGeneralData ();
    void setUnitData ();
    void setBatimentData ();
    void displayUI (sf::RenderWindow* window);
    ~UI ();
    // Setters and Getters
  };

};

#endif
