// Generated by dia2code
#ifndef RENDER__UNITETILESET__H
#define RENDER__UNITETILESET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
  class TileSet;
}

#include "Tile.h"
#include "TileSet.h"

namespace render {

  /// class UniteTileSet - 
  class UniteTileSet : public render::TileSet {
    // Attributes
  private:
    std::vector<Tile> unites;
    // Operations
  public:
    UniteTileSet ();
    ~UniteTileSet ();
    int const getWidth ();
    int const getHeigth ();
    std::string const getImageFile ();
    // Setters and Getters
  };

};

#endif
