// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include <vector>

namespace engine {
  class Engine;
};
namespace state {
  class Jeu;
};
namespace engine {
  class Command;
}

#include "engine/Command.h"
#include "state/Jeu.h"

namespace ai {

  /// class AI - 
  class AI {
    // Attributes
  public:
    int player_id;
    engine::Engine* engine;
    state::Jeu* jeu;
    std::vector<state::Unite*> liste_unites;
    std::vector<state::Batiment> liste_batiments;
    std::vector<state::Flag*> liste_flag_enemies;
    // Operations
  public:
    void DeplacerUnite ();
    Unite& CreerUnite ();
    void Attack (state::Position pos);
    void SelecUnite ();
    virtual void Run () = 0;
    // Setters and Getters
  };

};

#endif
