// Generated by dia2code
#ifndef AI__HEURISTICAI__H
#define AI__HEURISTICAI__H

#include <random>
#include <vector>

namespace engine {
  class Engine;
};
namespace state {
  class Jeu;
};
namespace engine {
  class Command;
};
namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class HeuristicAI - 
  class HeuristicAI : public ai::AI {
    // Attributes
  public:
    std::mt19937 randeng;
    int color;
    /// 			
    engine::Engine* engine;
    state::Jeu* jeu;
    std::vector<state::Unite*> liste_unites;
    std::vector<state::Batiment*> liste_batiments;
    std::vector<engine::Command*> liste_commands;
    std::vector<int> liste_poids;
    std::vector<state::Flag*> liste_flags_ennemie;
    state::Flag* flag_allies;
    std::vector<state::Unite*> liste_ennemies;
    // Operations
  public:
    HeuristicAI ();
    HeuristicAI (int color, engine::Engine* engine, state::Jeu* jeu);
    void fillStateList ();
    void fillCommandList ();
    void run ();
    void poidCommande ();
    ~HeuristicAI ();
    void poidDistance ();
    std::vector<state::Position> enemyCote (state::Position pos);
    // Setters and Getters
  };

};

#endif
