// Generated by dia2code
#ifndef AI__RANDOMAI__H
#define AI__RANDOMAI__H

#include <random>
#include <vector>

namespace engine {
  class Engine;
};
namespace state {
  class Jeu;
};
namespace engine {
  class Command;
};
namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class RandomAI - 
  class RandomAI : public ai::AI {
    // Attributes
  public:
    std::mt19937 randeng;
    int color;
    /// 			
    engine::Engine* engine;
    state::Jeu* jeu;
    std::vector<state::Unite*> liste_unites;
    std::vector<state::Batiment*> liste_batiments;
    std::vector<engine::Command*> liste_commands;
    // Operations
  public:
    RandomAI ();
    RandomAI (int color, engine::Engine* engine, state::Jeu* jeu);
    void fillStateList ();
    void fillCommandList ();
    void run ();
    ~RandomAI ();
    // Setters and Getters
  };

};

#endif
