// Generated by dia2code
#ifndef AI__RANDOMAI__H
#define AI__RANDOMAI__H

#include <random>

namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class RandomAI - 
  class RandomAI : public ai::AI {
    // Attributes
  public:
    std::mt19937 randeng;
     player_id;
    // Operations
  public:
    RandomAI ();
    RandomAI (int player_id);
    void run ();
    ~RandomAI ();
    // Setters and Getters
  };

};

#endif
