// Generated by dia2code
#ifndef ENGINE__ATTACKUNITCOMMAND__H
#define ENGINE__ATTACKUNITCOMMAND__H


namespace state {
  class Jeu;
};
namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class AttackUnitCommand - 
  class AttackUnitCommand : public engine::Command {
    // Attributes
  public:
    state::Position objectPos;
    state::Position targetPos;
    // Operations
  public:
    AttackUnitCommand ();
    AttackUnitCommand (state::Position objectPos, state::Position targetPos);
    ~AttackUnitCommand ();
    void execute (state::Jeu* jeu);
    // Setters and Getters
  };

};

#endif
