// Generated by dia2code
#ifndef ENGINE__ATTACKUNITCOMMAND__H
#define ENGINE__ATTACKUNITCOMMAND__H


namespace state {
  class Jeu;
};
namespace engine {
  class Engine;
  class Command;
}

#include "Command.h"

namespace engine {

  /// class AttackUnitCommand - 
  class AttackUnitCommand : public engine::Command {
    // Attributes
  public:
    state::Position objectPos;
    state::Position targetPos;
    int id     = 4;
    int target_life;
    int target_power;
    // Operations
  public:
    AttackUnitCommand ();
    AttackUnitCommand (state::Position targetPos);
    ~AttackUnitCommand ();
    void execute (state::Jeu* jeu, Engine* engine);
    state::Position getPos ();
    int getId ();
    void Undo (state::Jeu* jeu, Engine* engine);
    // Setters and Getters
  };

};

#endif
