// Generated by dia2code
#ifndef ENGINE__CAPTUREFLAGCOMMAND__H
#define ENGINE__CAPTUREFLAGCOMMAND__H


namespace state {
  class Jeu;
};
namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class CaptureFlagCommand - 
  class CaptureFlagCommand : public engine::Command {
    // Attributes
  public:
    state::Position objectPos;
    // Operations
  public:
    CaptureFlagCommand ();
    CaptureFlagCommand (state::Position objectPos);
    ~CaptureFlagCommand ();
    void execute (state::Jeu* jeu);
    // Setters and Getters
  };

};

#endif
