// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H

#include <json/json.h>

namespace state {
  class Jeu;
};
namespace engine {
  class Engine;
}

#include "state/Jeu.h"

namespace engine {

  /// class Command - 
  class Command {
    // Attributes
  public:
    int id;
    // Operations
  public:
    Command ();
    virtual ~Command ();
    virtual void execute (state::Jeu* jeu, Engine* engine) = 0;
    virtual void Undo (state::Jeu* jeu, Engine* engine) = 0;
    virtual state::Position getPos () = 0;
    virtual int getId () = 0;
    virtual Json::Value toJson () = 0;
    // Setters and Getters
  };

};

#endif
