// Generated by dia2code
#ifndef ENGINE__CREATEUNITCOMMAND__H
#define ENGINE__CREATEUNITCOMMAND__H


namespace state {
  class Jeu;
};
namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class CreateUnitCommand - 
  class CreateUnitCommand : public engine::Command {
    // Attributes
  public:
    int id     = 0;
    // Operations
  public:
    CreateUnitCommand ();
    ~CreateUnitCommand ();
    void execute (state::Jeu* jeu);
    state::Position getPos ();
    // Setters and Getters
  };

};

#endif
