// Generated by dia2code
#ifndef ENGINE__DELETEUNITCOMMAND__H
#define ENGINE__DELETEUNITCOMMAND__H

#include <json/json.h>

namespace state {
  class Jeu;
};
namespace engine {
  class Engine;
  class Command;
}

#include "Command.h"

namespace engine {

  /// class DeleteUnitCommand - 
  class DeleteUnitCommand : public engine::Command {
    // Attributes
  public:
    state::Position objectPos;
    int id     = 1;
    int target_type;
    int target_color;
    // Operations
  public:
    DeleteUnitCommand ();
    DeleteUnitCommand (state::Position objectPos);
    ~DeleteUnitCommand ();
    void execute (state::Jeu* jeu, Engine* engine);
    state::Position getPos ();
    int getId ();
    void Undo (state::Jeu* jeu, Engine* engine);
    Json::Value toJson ();
    // Setters and Getters
  };

};

#endif
