// Generated by dia2code
#ifndef ENGINE__DELETEUNITCOMMAND__H
#define ENGINE__DELETEUNITCOMMAND__H


namespace state {
  class Jeu;
};
namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class DeleteUnitCommand - 
  class DeleteUnitCommand : public engine::Command {
    // Attributes
  public:
    state::Position objectPos;
    // Operations
  public:
    DeleteUnitCommand ();
    DeleteUnitCommand (state::Position objectPos);
    ~DeleteUnitCommand ();
    void execute (state::Jeu* jeu);
    // Setters and Getters
  };

};

#endif
