// Generated by dia2code
#ifndef ENGINE__ENDTURNCOMMAND__H
#define ENGINE__ENDTURNCOMMAND__H


namespace state {
  class Jeu;
};
namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class EndTurnCommand - 
  class EndTurnCommand : public engine::Command {
    // Operations
  public:
    EndTurnCommand ();
    ~EndTurnCommand ();
    void execute (state::Jeu* jeu);
    // Setters and Getters
  };

};

#endif
