// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include <vector>

namespace state {
  class Jeu;
};
namespace engine {
  class Command;
  class Engine_Observable;
}

#include "Engine_Observable.h"
#include "Command.h"

namespace engine {

  /// class Engine - 
  class Engine : public engine::Engine_Observable {
    // Associations
    // Attributes
  public:
    state::Jeu* jeu;
    std::vector<Command*> commands;
    Command* latest_command;
    // Operations
  public:
    Engine ();
    Engine (state::Jeu* jeu);
    ~Engine ();
    void addCommand (Command* command);
    void update ();
    void Clear ();
    void RollBack ();
    // Setters and Getters
  };

};

#endif
