// Generated by dia2code
#ifndef ENGINE__SELECTUNITCOMMAND__H
#define ENGINE__SELECTUNITCOMMAND__H


namespace state {
  class Jeu;
};
namespace engine {
  class Engine;
  class Command;
}

#include "Command.h"

namespace engine {

  /// class SelectUnitCommand - 
  class SelectUnitCommand : public engine::Command {
    // Attributes
  public:
    state::Position objectPos;
    int id     = 2;
    // Operations
  public:
    SelectUnitCommand ();
    SelectUnitCommand (state::Position objectPos);
    ~SelectUnitCommand ();
    void execute (state::Jeu* jeu, Engine* engine);
    state::Position getPos ();
    int getId ();
    void Undo (state::Jeu* jeu, Engine* engine);
    // Setters and Getters
  };

};

#endif
