// Generated by dia2code
#ifndef CLIENT__CLIENT__H
#define CLIENT__CLIENT__H


namespace engine {
  class Engine;
};
namespace state {
  class Jeu;
};
namespace ai {
  class HeuristicAI;
};
namespace engine {
  class Engine_Observer;
};
namespace render {
  class Layers;
}

#include "engine/Engine_Observer.h"
#include "render/Layers.h"
#include "ai/HeuristicAI.h"
#include "engine/Engine.h"
#include "state/Jeu.h"

namespace client {

  /// class Client - 
  class Client : public engine::Engine_Observer {
    // Associations
    // Attributes
  public:
    engine::Engine* engine;
    state::Jeu* jeu;
    ai::HeuristicAI* ai1;
    ai::HeuristicAI* ai2;
    // Operations
  public:
    Client ();
    Client (state::Jeu* jeu);
    void engineUpdating ();
    void engineUpdated ();
    void run ();
    ~Client ();
    // Setters and Getters
  };

};

#endif
