// Generated by dia2code
#ifndef CLIENT__CLIENT__H
#define CLIENT__CLIENT__H


namespace engine {
  class Engine;
};
namespace state {
  class Jeu;
};
namespace render {
  class Layers;
};
namespace ai {
  class HeuristicAI;
}

#include "ai/HeuristicAI.h"
#include "render/Layers.h"
#include "engine/Engine.h"
#include "state/Jeu.h"

namespace client {

  /// class Client - 
  class Client {
    // Associations
    // Attributes
  public:
    engine::Engine* engine;
    state::Jeu* jeu;
    render::Layers* layers;
    // Operations
  public:
    Client ();
    void engineUpdating ();
    void engineUpdated ();
    run ();
    // Setters and Getters
  };

};

#endif
