// Generated by dia2code
#ifndef __RENDER__H
#define __RENDER__H

#include "render/Tile.h"
#include "render/TileSet.h"
#include "render/Layer.h"
#include "render/Tilemap.h"
#include "render/TerrainTileSet.h"
#include "render/UniteTileSet.h"
#include "render/BatimentTileSet.h"
#endif
